sudo: false
nguage: cpp

install:
  # /usr/bin/gcc is 4.6 always, but gcc-X.Y is available.
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  # /usr/bin/clang is 3.4, lets override with modern one.
  - if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - echo ${PATH}
  - echo ${CXX}
  - ${CXX} --version
  - ${CXX} -v

os:
  - linux
  - osx

language: cpp

compiler:
  - gcc
  - clang

before_script:  
  - mkdir build
  - cd build
  - cmake ..

script: make  

addons:
 apt:
  sources:
   - george-edison55-precise-backports
   - ubuntu-toolchain-r-test
   - llvm-toolchain-precise-3.7
  packages:
   - cmake
   - cmake-data
   - gcc-4.9
   - g++-4.9
   - clang-3.7
